### ISSUE TITLE
Fix -Wpointer-bool-conversion for target.default_app_name,default_msgid

### ISSUE THREAD

**Issue by matthew-macgregor** [goatshriek/stumpless#261] opened 2022-10-12 03:12 UTC
**Describe the bug**

I noticed the following warnings while building and running tests. `default_app_name` and `default_msgid` addresses will always evaluate to true.

https://clang.llvm.org/docs/DiagnosticsReference.html#wpointer-bool-conversion

```
[build] /Users/matsu/Code/repos/stumpless/src/target.c:402:16: warning: address of array 'target->default_app_name' will always evaluate to 'true' [-Wpointer-bool-conversion]
[build]   if( !target->default_app_name ) {
[build]       ~~~~~~~~~^~~~~~~~~~~~~~~~
[build] /Users/matsu/Code/repos/stumpless/src/target.c:429:16: warning: address of array 'target->default_msgid' will always evaluate to 'true' [-Wpointer-bool-conversion]
[build]   if( !target->default_msgid ) {
[build]       ~~~~~~~~~^~~~~~~~~~~~~
[build] 2 warnings generated.
```

**Build Environment**
Describe your build environment and any other factors that contribute to the configuration of Stumpless. This should include:
 * macOS 12.5.1
 * Clang 13.1.6 x86_64-apple-darwin21.6.0
 * Build `all` target

**Comment by saadsheriff** [comment] 2022-10-14 06:43
Can I get assigned to this issue? I think I got it!

**Comment by goatshriek** [comment] 2022-10-14 12:22
Sure thing!

**Comment by goatshriek** [comment] 2023-08-24 10:34
Hello @saadsheriff, I'm just checking in to see if you still intend to work on this issue? It is not a problem if not, I can remove your assignment and open it up for others to resolve.

**Comment by EralpCelebi** [comment] 2024-01-15 22:17
Does this problem still persist? I was unable to reproduce these results and it seems like the source of the problem has already been refactored.

**Comment by goatshriek** [comment] 2024-01-16 15:00
I believe you are correct @EralpCelebi, a [recent Mac CI run](https://github.com/goatshriek/stumpless/actions/runs/7519896822/job/20533936824) does not exhibit the noted warning. Thank you very much for raising this! As you said, a different refactoring effort must have taken care of this incidentally.

If you are looking for opportunities to contribute, there is a different compiler warning in `stumpless_prival_from_string` noted in the "Build" stage of the above CI run:

```
/Users/runner/work/stumpless/stumpless/src/priority.c:92:16: warning: multiple unsequenced modifications to 'len' [-Wunsequenced]
  len = slen - ++len;
      ~        ^
1 warning generated.
```

Please consider giving this function some attention with a refactor to remove the warning and perhaps make things a bit cleaner. Thank you again for confirming this issue as resolved!

**Closed as completed by goatshriek** 2024-01-16 15:00 UTC
Labels: help wanted, good first issue

**Comment by EralpCelebi** [comment] 2024-01-18 15:10
No problem! I'll look into it whenever I have the time.

**Comment by EralpCelebi** [comment] 2024-01-18 22:32
@goatshriek I have created a pull request for a small fix. #401
